FROM node:23.11.1-alpine3.21
LABEL maintainer="ptrcnull <github@ptrcnull.me>"

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --ignore-scripts

COPY . .

RUN yarn compile

CMD [ "yarn", "start" ]
